// swift-tools-version: 6.1
// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 wilmtang. Part of MonitorFlux, free software under the GNU
// Affero General Public License v3.0 or later. See LICENSE. No warranty.

import PackageDescription

let package = Package(
    name: "MonitorFlux",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .executable(name: "MonitorFlux", targets: ["MonitorFlux"])
    ],
    targets: [
        .executableTarget(
            name: "MonitorFlux",
            path: "Sources/MonitorFlux",
            resources: [
                // Offline city/ZIP index for the Follow-sunset location search; regenerated by
                // script/make_place_index.swift. build_and_run.sh copies the SwiftPM resource
                // bundle into the .app's Contents/Resources (PlaceIndex looks for it there).
                .copy("Resources/places.tsv")
            ],
            linkerSettings: [
                .linkedFramework("AppKit"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("CoreLocation"),
                .linkedFramework("IOKit"),
                .linkedFramework("ServiceManagement"),
                .linkedFramework("SwiftUI")
            ]
        ),
        .testTarget(
            name: "MonitorFluxTests",
            dependencies: ["MonitorFlux"],
            path: "Tests/MonitorFluxTests"
        )
    ]
)
